### ISSUE TITLE
Errors when I run in Vim or Neovim

### ISSUE THREAD

**Issue by superquest** [liuchengxu/space-vim#55] opened 2017-02-01 13:26 UTC
#### Environment

- OS: MacOS 10.11.6
- vim: 
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 14 2016 16:06:49)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn 
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs 
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses

- neovim:
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170201-7304-eqlwvz/neovim-0.1.7/build/config -I/tmp/neovim-20170201-7304-eqlwvz/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170201-7304-eqlwvz/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170201-7304-eqlwvz/neovim-0.1.7/build/include
Compiled by justin@personal

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"

##### When I install space-vim according to instructions, symlink `~/.config/nvim/init.vim`, and then run `nvim`, I get the following error:

Error detected while processing function <SNR>2_collect_topics:
line   26:
E117: Unknown function: provider#python3#Call
Error detected while processing function core_config#end[6]..<SNR>2_load_layer_packages:
line    2:
E121: Undefined variable: g:layer_path
E15: Invalid expression: g:layer_path[l:layer] . '/packages.vim'
line    3:
E121: Undefined variable: l:layer_packages
E116: Invalid arguments for function <SNR>2_Source
line    2:
E121: Undefined variable: g:layer_path
E15: Invalid expression: g:layer_path[l:layer] . '/packages.vim'
line    3:
E121: Undefined variable: l:layer_packages
E116: Invalid arguments for function <SNR>2_Source
line    2:
E121: Undefined variable: g:layer_path
E15: Invalid expression: g:layer_path[l:layer] . '/packages.vim'
line    3:
E121: Undefined variable: l:layer_packages
E116: Invalid arguments for function <SNR>2_Source
line    2:
E121: Undefined variable: g:layer_path
E15: Invalid expression: g:layer_path[l:layer] . '/packages.vim'
line    3:
E121: Undefined variable: l:layer_packages
E116: Invalid arguments for function <SNR>2_Source
Error detected while processing function core_config#end[33]..<SNR>2_load_layer_config:
line    2:
E121: Undefined variable: g:layer_path
E15: Invalid expression: g:layer_path[l:layer] . '/config.vim'
line    3:
E121: Undefined variable: l:layer_config
E116: Invalid arguments for function <SNR>2_Source
line    2:
E121: Undefined variable: g:layer_path
E15: Invalid expression: g:layer_path[l:layer] . '/config.vim'
line    3:
E121: Undefined variable: l:layer_config
E116: Invalid arguments for function <SNR>2_Source
line    2:
E121: Undefined variable: g:layer_path
E15: Invalid expression: g:layer_path[l:layer] . '/config.vim'
line    3:
E121: Undefined variable: l:layer_config
E116: Invalid arguments for function <SNR>2_Source
line    2:
E121: Undefined variable: g:layer_path
E15: Invalid expression: g:layer_path[l:layer] . '/config.vim'
line    3:
E121: Undefined variable: l:layer_config
E116: Invalid arguments for function <SNR>2_Source
Press ENTER or type command to continue

##### When I run `vim`, I get the following error:

Error detected while processing VimEnter Auto commands for "*":
E492: Not an editor command:       Startify|  endif
Press ENTER or type command to continue

**Comment by liuchengxu** [comment] 2017-02-01 13:35
It looks like neovim can't call python. 

`:echo has("python3")`, if it's 0, try `pip3 install neovim`.

**Comment by liuchengxu** [comment] 2017-02-01 14:27
@superquest I notice that your vim version is still vim7.3. Since you are using mac, you could update to the vim8 easily with brew, then many better plugins could play their roles. The async feature in vim8 is really cool 😃.  

For the error in vim, does it still persist? I'm a little confused about this error. Just make no sense 🙉 .

**Comment by onewildgamer** [comment] 2017-02-01 15:36
I have the exact same error, I'm running on ubuntu 14.04 and vim8

**Comment by superquest** [comment] 2017-02-01 16:43
installing neovim made that big ugly error go away.

But I still get the following error with both vim and neovim:

Error detected while processing VimEnter Auto commands for "*":
E492: Not an editor command:       Startify|  endif

**Comment by wsdjeg** [comment] 2017-02-01 16:48
It is space-vim, when run this autocmd ,should check if the command exist.
@liuchengxu  I think you should check if `exists(':Startify') == 2`.

**Comment by liuchengxu** [comment] 2017-02-01 23:02
@wsdjeg Yeah, but it's not the root cause. https://github.com/liuchengxu/space-vim/blob/master/core/autoload/core_config.vim#L420-L425 , vim-plug will automatically install the missing plugins in enabled layers.

@superquest @onewildgamer Could you check if vim-startify have already been installed? `:PlugStatus` to see the all plugins' status, or `:echo exists(':Startify')` see it's 2, if not, please run `:PlugInstall` manually.

**Comment by liuchengxu** [comment] 2017-02-02 01:33
@superquest @onewildgamer  I suspect that there's something wrong with vim-startify.

I have tested in the two cases:

- `UserInit()`
    Add a new plugin into `UserInit()` in `.spacevim`, e.g., 

    ```
    Plug 'mbbill/undotree',             { 'on': 'UndotreeToggle'   }
    ```
    vim-plug will automatically install the misssing undotree plugin successfully.

- `packages.vim`
    Pick out randomly one plugin in the layer's packages.vim, e.g., 

   ```
   " MP 'scrooloose/nerdcommenter',        { 'on': '<Plug>NERDCommenterToggle' }
   ```
   1. comment it, then reopen vim and run `:PlugClean` to clean the archive.
   2. uncomment the above MP command, vim-plug will succeed to install the missing nerdcommenter plugin too.
   3. repeat the operations on vim-startify with difficulty (because it raises an error below), vim-plug fails to install this one plugin. You need to install it manually with `:PlugInstall`.
   
   ```
   Error detected while processing function cursorword#matchadd:
   line   13:
   E28: No such highlight group name: CursorWord0
   Press ENTER or type command to continue
   ```
   
   The error is seemingly related to [vim-cursorword](itchyny/vim-cursorword). After finishing the vim-startify installation, everything is ok. Do you have any suggestions here? @mhinz ?

**Comment by mhinz** [comment] 2017-02-02 02:35
@liuchengxu 

There were no installation issues for a very long time, so I doubt it's an issue with Startify.

I don't know enough about how space-vim works to give a meaningful answer. You said that manually using `:PlugInstall` works, so.. maybe it's one of the commands (`:MP` I guess?) you use to load/install plugins that breaks it?

**Comment by superquest** [comment] 2017-02-02 05:52
@liuchengxu: `:PlugStatus` returns the following: 
![image](https://cloud.githubusercontent.com/assets/4335621/22538591/774a06ae-e94e-11e6-965c-fce26467c9e4.png)

Running `:PlugInstall` made all the problems go away!

**Comment by liuchengxu** [comment] 2017-02-02 11:07
@superquest Really happy to hear this!  🎉 
 Since more than one user encountered this issue. I'm still trying to reproduce it. Hope I can find the primary cause. 😃 

@mhinz Thanks for your response. In fact, `MP` is merely a simple wrapper for `Plug` command. I'll pay more attention to this. Maybe it is `MP` that actually caused the problem. 😭

**Comment by liuchengxu** [comment] 2017-03-18 13:39
I have refactored the related code. Since there is no similar issue opened for some time, we can close this.

**Closed by liuchengxu** 2017-03-18 13:39 UTC

**Comment by hieudang9** [comment] 2017-03-26 09:38
I faced the same issue. Vim 7.4 on Debian jessie

**Comment by liuchengxu** [comment] 2017-03-26 09:43
@hieudang9 Could it be solved by running `:PlugInstall` manually?

**Comment by hieudang9** [comment] 2017-03-26 12:00
@liuchengxu Hi, I realize my vim is `Small version without GUI`. So try to install `vim-gui-common` and `vim-runtime`, run `:PlugInstall` then It's work.
